### ISSUE TITLE
<string>:14: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html

### ISSUE THREAD

**Issue by T1Founder** [Phxnt0m1/Phxnt0mWare-Grabber#67]
<string>:14: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html

getting this error. any1 know how to fix?

**Comment by Phxnt0m1** [comment]
Please message me on deadlock03. for help with this issue.
